### ISSUE TITLE
Fail to install by using setup.py

### ISSUE THREAD

**Issue by CiaoHe** [usnistgov/COSMOSAC#19]
Hi!
I'm new to cmake. So when I run `python setup.py install`, it turns out such an error:

```
running bdist_egg
running egg_info
writing cCOSMO.egg-info\PKG-INFO
writing dependency_links to cCOSMO.egg-info\dependency_links.txt
writing top-level names to cCOSMO.egg-info\top_level.txt
reading manifest file 'cCOSMO.egg-info\SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'cCOSMO.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
CMake Error at CMakeLists.txt:1 (project):
  Generator

    NMake Makefiles

  does not support platform specification, but platform

    x64

  was specified.


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
```

Env:
I'm using Windows10, and have installed `cmake` and `gcc` and `g++`(both using mingw64).

Could you give some suggestions? Many thanks!

**Comment by ianhbell** [comment]
Somehow NMake is your default generator.  Can you please show the full set of shell output?

**Comment by ianhbell** [comment]
Don't use mingw would be my recommendation.  Visual Studio is your best bet.  Or run in a docker container.

**Comment by CiaoHe** [comment]
Hi, thanks for your reply! Here is the full shell output:

```
❯ python setup.py install
running install
C:\Users\hecao\anaconda3\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
C:\Users\hecao\anaconda3\lib\site-packages\setuptools\command\easy_install.py:156: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
C:\Users\hecao\anaconda3\lib\site-packages\pkg_resources\__init__.py:116: PkgResourcesDeprecationWarning: 4.0.0-unsupported is an invalid version and will not be supported in a future release
  warnings.warn(
running bdist_egg
running egg_info
creating cCOSMO.egg-info
writing cCOSMO.egg-info\PKG-INFO
writing dependency_links to cCOSMO.egg-info\dependency_links.txt
writing top-level names to cCOSMO.egg-info\top_level.txt
writing manifest file 'cCOSMO.egg-info\SOURCES.txt'
reading manifest file 'cCOSMO.egg-info\SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'cCOSMO.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
-- Building for: NMake Makefiles
CMake Error at CMakeLists.txt:1 (project):
  Generator

    NMake Makefiles

  does not support platform specification, but platform

    x64

  was specified.


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "C:/Users/hecao/cosmosac/COSMOSAC/build/temp.win-amd64-3.9/Release/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "C:\Users\hecao\COSMOSAC\COSMOSAC\setup.py", line 62, in <module>
    setup(
  File "C:\Users\hecao\anaconda3\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\hecao\anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\hecao\anaconda3\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\hecao\anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\hecao\anaconda3\lib\site-packages\setuptools\command\install.py", line 74, in run
    self.do_egg_install()
  File "C:\Users\hecao\anaconda3\lib\site-packages\setuptools\command\install.py", line 116, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\hecao\anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\hecao\anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\hecao\anaconda3\lib\site-packages\setuptools\command\bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\hecao\anaconda3\lib\site-packages\setuptools\command\bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "C:\Users\hecao\anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\hecao\anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\hecao\anaconda3\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Users\hecao\anaconda3\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Users\hecao\anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\hecao\anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\hecao\COSMOSAC\COSMOSAC\setup.py", line 34, in run
    self.build_extension(ext)
  File "C:\Users\hecao\COSMOSAC\COSMOSAC\setup.py", line 59, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "C:\Users\hecao\anaconda3\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\hecao\\COSMOSAC\\COSMOSAC', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\hecao\\COSMOSAC\\COSMOSAC\\build\\lib.win-amd64-3.9', '-DPYTHON_EXECUTABLE=C:\\Users\\hecao\\anaconda3\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\hecao\\COSMOSAC\\COSMOSAC\\build\\lib.win-amd64-3.9', '-A', 'x64']' returned non-zero exit status 1.
```

And I will try Visual Studio instead of MinGW. Thanks!

**Comment by ianhbell** [comment]
The build expects the Makefiles generator to be default for cmake, but somehow your cmake defaults to NMake.  Can you set yours to default back to Makefiles?

**Comment by CiaoHe** [comment]
yeah, I will fix it. Thanks for your suggestion!
