### ISSUE TITLE
Unable to install cCOSMO using cygwin

### ISSUE THREAD

**Issue by smwaziri** [usnistgov/COSMOSAC#28]
$ python3 setup.py install
running install
/usr/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3.9/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
creating cCOSMO.egg-info
writing cCOSMO.egg-info/PKG-INFO
writing dependency_links to cCOSMO.egg-info/dependency_links.txt
writing top-level names to cCOSMO.egg-info/top_level.txt
writing manifest file 'cCOSMO.egg-info/SOURCES.txt'
reading manifest file 'cCOSMO.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'cCOSMO.egg-info/SOURCES.txt'
installing library code to build/bdist.cygwin-3.4.6-x86_64/egg
running install_lib
running build_ext
-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.1
CMake Warning at /usr/share/cmake-3.25.3/Modules/Platform/CYGWIN.cmake:15 (message):
  CMake no longer defines WIN32 on Cygwin!

  (1) If you are just trying to build this project, ignore this warning or
  quiet it by setting CMAKE_LEGACY_CYGWIN_WIN32=0 in your environment or in
  the CMake cache.  If later configuration or build errors occur then this
  project may have been written under the assumption that Cygwin is WIN32.
  In that case, set CMAKE_LEGACY_CYGWIN_WIN32=1 instead.

  (2) If you are developing this project, add the line

    set(CMAKE_LEGACY_CYGWIN_WIN32 0) # Remove when CMake >= 2.8.4 is required

  at the top of your top-level CMakeLists.txt file or set the minimum
  required version of CMake to 2.8.4 or higher.  Then teach your project to
  build on Cygwin without WIN32.
Call Stack (most recent call first):
  /usr/share/cmake-3.25.3/Modules/CMakeSystemSpecificInformation.cmake:45 (include)
  CMakeLists.txt:1 (project)

-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- pybind11 v2.11.0 dev1
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.9.16", minimum required is "3.6")
-- Found PythonLibs: /usr/lib/libpython3.9.dll.a
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/Prof. S.M. Waziri/cosmosac-v1.0/usnistgov-COSMOSAC-9f1a55a/build/temp.cygwin-3.4.6-x86_64-cpython-39
[ 50%] Building CXX object CMakeFiles/cCOSMO.dir/src/pybind11_interface.cxx.o
[100%] Linking CXX shared module "/home/Prof. S.M. Waziri/cosmosac-v1.0/usnistgov-COSMOSAC-9f1a55a/build/lib.cygwin-3.4.6-x86_64-cpython-39/cCOSMO.cpython-39-x86_64-cygwin.dll"
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: /tmp/ccd2bDM9.ltrans1.ltrans.o:<artificial>:(.text+0x13): undefined reference to `__imp_PyProperty_Type'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: /tmp/ccd2bDM9.ltrans1.ltrans.o:<artificial>:(.text+0x42): undefined reference to `__imp_PyProperty_Type'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: /tmp/ccd2bDM9.ltrans1.ltrans.o:<artificial>:(.text+0x2f30): undefined reference to `__imp_PyExc_IndexError'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: /tmp/ccd2bDM9.ltrans6.ltrans.o:<artificial>:(.text.unlikely+0xb9): undefined reference to `PyErr_Occurred'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: /tmp/ccd2bDM9.ltrans6.ltrans.o:<artificial>:(.text.unlikely+0xde): undefined reference to `PyErr_SetString'
collect2: error: ld returned 1 exit status
make[3]: *** [CMakeFiles/cCOSMO.dir/build.make:97: /home/Prof. S.M. Waziri/cosmosac-v1.0/usnistgov-COSMOSAC-9f1a55a/build/lib.cygwin-3.4.6-x86_64-cpython-39/cCOSMO.cpython-39-x86_64-cygwin.dll] Error 1
make[2]: *** [CMakeFiles/Makefile2:130: CMakeFiles/cCOSMO.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:137: CMakeFiles/cCOSMO.dir/rule] Error 2
make: *** [Makefile:137: cCOSMO] Error 2
Traceback (most recent call last):
  File "/home/Prof. S.M. Waziri/cosmosac-v1.0/usnistgov-COSMOSAC-9f1a55a/setup.py", line 67, in <module>
    setup(
  File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 108, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/usr/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/usr/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.9/site-packages/setuptools/dist.py", line 1221, in run_command
    super().run_command(command)
  File "/usr/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.9/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/usr/lib/python3.9/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.9/site-packages/setuptools/dist.py", line 1221, in run_command
    super().run_command(command)
  File "/usr/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.9/site-packages/setuptools/dist.py", line 1221, in run_command
    super().run_command(command)
  File "/usr/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.9/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/usr/lib/python3.9/site-packages/setuptools/_distutils/command/install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "/usr/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.9/site-packages/setuptools/dist.py", line 1221, in run_command
    super().run_command(command)
  File "/usr/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/S.M. Waziri/cosmosac-v1.0/usnistgov-COSMOSAC-9f1a55a/setup.py", line 35, in run
    self.build_extension(ext)
  File "/home/S.M. Waziri/cosmosac-v1.0/usnistgov-COSMOSAC-9f1a55a/setup.py", line 63, in build_extension
    subprocess.check_call(
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'cCOSMO', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2.

**Comment by ianhbell** [comment]
The short answer is use WSL or docker or something similar. I have never had good success with cygwin

**Comment by smwaziri** [comment]
Ok, thank you for the suggestion.
